" VIMRC

" Plugins {{{
filetype off
call plug#begin('~/.vim/plug')

Plug 'lervag/vimtex'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Valloric/YouCompleteMe'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'honza/vim-snippets'
Plug 'garbas/vim-snipmate'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'rhysd/vim-grammarous'
Plug 'othree/html5.vim'
Plug 'rdnetto/YCM-Generator'

" Themes
Plug 'bluz71/vim-moonfly-colors'
Plug 'whatyouhide/vim-gotham'

call plug#end()
filetype plugin indent on
" }}}
" General {{{
set nocompatible
set backspace=indent,eol,start

set ruler
set showcmd
set number

set incsearch
set nohlsearch
set ignorecase
set smartcase

set shiftwidth=4
set softtabstop=0
set tabstop=4
set expandtab
set autoindent

set foldenable
set foldmethod=syntax

set spell spelllang=en_au
set spell

if has('mouse')     " disable the mouse in the terminal
    set mouse=c
endif

" }}}
" Theme {{{
colorscheme moonfly
set cursorline
set nohlsearch
syntax on
highlight Normal ctermbg=NONE
highlight CursorLine ctermbg=0
highlight CursorLineNr ctermbg=9 ctermfg=0
highlight LineNr ctermbg=0 ctermfg=7
highlight Folded ctermbg=none ctermfg=7
highlight SpellBad ctermbg=0
highlight ErrorMsg ctermfg=2
highlight MoreMsg ctermfg=3
highlight Comment ctermfg=12
highlight shShellVariables ctermfg=1
"}}}
" Bindings {{{

let mapleader = "\\"
map Q gq 		" disable Ex mode, use q for formatting

nmap <silent> <C-l> :wincmd l<cr>
nmap <silent> <C-h> :wincmd h<cr>
nmap <silent> <C-j> :wincmd j<cr>
nmap <silent> <C-k> :wincmd k<cr>

" }}}
" Functions {{{

" see changes made since it was loaded
if !exists(":DiffOrig")
    command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
                \ | wincmd p | diffthis
endif

" }}}
" Markdown Bindings {{{
nnoremap <leader>c :!fname=%; pandoc -o ${fname\%.md}.pdf %<cr>
nnoremap <leader>p :silent !fname=%; zathura ${fname\%.md}.pdf &<cr>
" }}}
" Airline {{{
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'lucius'
" }}}
" Ale {{{
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1

let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_sign_info = '! '
let g:ale_sign_style_error = '* '
let g:ale_sign_style_warning = '+ '
let g:ale_sign_column_always = 1

let g:ale_enabled = 0
" }}}
" SnipMate {{{
imap <C-C> <C-R>=snipMate#TriggerSnippet(1)<CR>
" }}}
" Vimtex {{{
let g:vimtex_imaps_leader = ':'
" }}}
" Functions {{{

autocmd VimEnter *.tex :nnoremap <leader>c :!latexmk -ps %<CR>
" }}}

set modeline
" vim: foldmethod=marker:foldlevel=0
