#! /bin/sh

HEIGHT=20
FONT="xos4 terminus:size=8:antialias=true"
FONT_ICON="Knack Nerd Font:size=14:antialias=true"
FONT_ICON_SMALL="Knack Nerd Font:size=9:antialias=true"
FONT_ICON_LARGE="Knack Nerd Font:size=17:antialias=true"

# icons
GENTOO="\uf310"
ARCH="\uf300"
CSTART="\uf04b"
CSOUND="\uf001"
CVOLUME="\uf028"
CMAIL="\uf003"
CRAM="\uf473"
CCPU="\ue066"
CNET="\ue04b"
CWIFI="\uf1eb"
WIFI_STR="\uf1eb"
# Time
CTIME="\uf017"
CPACK="\ue1b7"
CCLOCK="\uf017"
# panel center
CNONE="\ue190"
CFULL="\ue0e6"
# icons panel music
CPREV="\uf049"
CNEXT="\uf04b"
CPLAY="\uf04a"
CPAUS="\uf04c"
# icon volume
VPLUS="\uf028"
VMINUS="\uf027"
# battery or AC
BAT100="\uf240"
BAT70="\uf241"
BAT50="\uf242"
BAT30="\uf243"
BAT15="\uf243"
BAT7="\uf244"
CAC="\uf0e7"

sepr() {
    echo $(pText ${SEPFG} ${SEPR})
}
sepl() {
    echo $(pText ${SEPFG} ${SEPL})
}

# $(pAction ${fg} ${bg} ${${command} ${whatprint})
pAction() {
    echo "%{F$1}%{B$2}%{A:$3:}$(printf '%b' $4)%{A}%{B-}%{F-}"
}

# $(pActionUnderline ${fg} ${bg} ${underline} ${${command} ${whatprint})
pActionUnderline() {
    echo "%{F$1}%{B$2}%{U$3}%{+u}%{A:$4:}$(printf '%b' $5)%{A}%{-u}%{B-}%{F-}"
}

# $(pIcon ${color} ${icon})
pIcon() {
    echo "%{F$1}$(printf '%b' "$2")%{F-}"
}

# $(pIconCustom ${color} ${icon} ${font-index})
pIconCustom() {
    echo "%{T$3}%{F$1}$(printf '%b' $2)%{F-}%{T-}"
}

# $(pIconUnderline ${color} ${color_underline} ${icon})
pIconUnderline() {
    echo "%{F$1}%{U$2}%{+u}$(printf '%b' $3)%{-u}%{F-}"
}

# $(pText ${color} ${text})
pText() {
    echo "%{F$1}$2%{F-}"
}

# $(pTextUnderline ${color} ${color_underline} ${text})
pTextUnderline() {
    echo "%{F$1}%{U$2}%{+u}$3%{-u}%{F-}"
}

getXresColor() {
   echo "$( xrdb -query | grep $1: | grep -oE '#[a-zA-Z0-9]{6}' | cut -c 1- )"
}

# colors
BG="#a0550000"
FG="$(getXresColor foreground)"
BLACK="$(getXresColor color0)"
BLACK2="$(getXresColor color8)"
RED="$(getXresColor color1)"
RED2="$(getXresColor color9)"
GREEN="$(getXresColor color9)"
GREEN2="$(getXresColor color10)"
YELLOW="$(getXresColor color3)"
YELLOW2="$(getXresColor color11)"
BLUE="$(getXresColor color4)"
BLUE2="$(getXresColor color2)"
MAGENTA="$(getXresColor color5)"
MAGENTA2="$(getXresColor color11)"
CYAN="$(getXresColor color12)"
CYAN2="$(getXresColor color14)" 
WHITE="$(getXresColor color7)"
WHITE2="$(getXresColor color15)"
SEPFG="$MAGENTA2"
SEPR=">>"
SEPL="<<"

# vim: set ft=sh
